name: HealthTag
version: 1.0
api: [1.3.1]
author: EnderKenji
description: Shows Player's Heath beside NameTag
main: HealthTag\HealthTag

commands:
 ht:
  default: op
  description: "Main HealthTag Command"
  usage: "/ht"
